[world]
description = "jokers_of_neon_lib"
name = "jokers_of_neon_lib"
seed = "jokers_of_neon_lib"

[namespace]
default = "jokers_of_neon_lib"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x6677fe62ee39c7b07401f754138502bab7fac99d2d3c5d37df7d1c6fab10819"
private_key = "0x3e3979c1ed728490308054fe357a9f49cf67f80f9721f44cc57235129e090f4"

[writers]
"jokers_of_neon_lib" = []

[[external_contracts]]
contract_name = "ERC721Token"
instance_name = "Jokers of Neon"
salt = "1"
constructor_data = ["0x2af9427c5a277474c079a1283c880ee8a6f0f8fbf73ce969c08d88befec1bba", "str:Jokers of Neon", "str:JN", "str:https://badge.com/" ]
