[package]
cairo-version = "=2.8.4"
name = "jokers_of_neon_lib"
version = "0.0.1"

[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.9" }

[lib]

[dev-dependencies]
cairo_test = "=2.8.4"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.9" }

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]