[package]
cairo-version = "2.13.1"
name = "jokers_of_neon_lib"
version = "0.20.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[dependencies]
dojo = "1.8.0"
dojo_cairo_macros = "1.8.0"
starknet = "2.13.1"

[dev-dependencies]
cairo_test = "=2.13.1"
dojo_cairo_test = "1.8.0"

[lib]
