pub const POKER_HAND_ROYAL_FLUSH: u32 = 1;
pub const POKER_HAND_STRAIGHT_FLUSH: u32 = 2;
pub const POKER_HAND_FIVE_OF_A_KIND: u32 = 3;
pub const POKER_HAND_FOUR_OF_A_KIND: u32 = 4;
pub const POKER_HAND_FULL_HOUSE: u32 = 5;
pub const POKER_HAND_STRAIGHT: u32 = 6;
pub const POKER_HAND_FLUSH: u32 = 7;
pub const POKER_HAND_THREE_OF_A_KIND: u32 = 8;
pub const POKER_HAND_TWO_PAIR: u32 = 9;
pub const POKER_HAND_ONE_PAIR: u32 = 10;
pub const POKER_HAND_HIGH_CARD: u32 = 11;


pub fn poker_hands_all() -> Array<u32> {
    array![
        POKER_HAND_ROYAL_FLUSH, POKER_HAND_STRAIGHT_FLUSH, POKER_HAND_FIVE_OF_A_KIND, POKER_HAND_FOUR_OF_A_KIND,
        POKER_HAND_FULL_HOUSE, POKER_HAND_STRAIGHT, POKER_HAND_FLUSH, POKER_HAND_THREE_OF_A_KIND, POKER_HAND_TWO_PAIR,
        POKER_HAND_ONE_PAIR, POKER_HAND_HIGH_CARD,
    ]
}
